<?php
/**
 * Fio Trans Cargo Website Installer
 * This installer will set up the database and configure the website
 */

// Prevent direct access after installation
if (file_exists('installed.lock')) {
    die('Website sudah terinstall. Hapus file "installed.lock" jika ingin menginstall ulang.');
}

$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;
$error = '';
$success = '';

// Handle form submissions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    switch ($step) {
        case 1:
            // Database configuration step
            $db_host = trim($_POST['db_host'] ?? '');
            $db_name = trim($_POST['db_name'] ?? '');
            $db_user = trim($_POST['db_user'] ?? '');
            $db_pass = $_POST['db_pass'] ?? '';
            
            if (empty($db_host) || empty($db_name) || empty($db_user)) {
                $error = 'Semua field database wajib diisi kecuali password.';
            } else {
                // Test database connection
                try {
                    $pdo = new PDO("mysql:host=$db_host", $db_user, $db_pass);
                    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
                    
                    // Create database if not exists
                    $pdo->exec("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                    $pdo->exec("USE `$db_name`");
                    
                    // Save database config to separate file
                    $config_content = "<?php
// Database configuration - Generated by installer
define('DB_HOST', '$db_host');
define('DB_NAME', '$db_name');
define('DB_USER', '$db_user');
define('DB_PASS', '$db_pass');
?>";
                    
                    file_put_contents('backend/config/db_config.php', $config_content);
                    
                    // Execute database schema
                    $schema = file_get_contents('backend/database/schema.sql');
                    $statements = explode(';', $schema);
                    
                    foreach ($statements as $statement) {
                        $statement = trim($statement);
                        if (!empty($statement)) {
                            $pdo->exec($statement);
                        }
                    }
                    
                    $success = 'Database berhasil dikonfigurasi!';
                    $step = 2;
                    
                } catch (PDOException $e) {
                    $error = 'Error database: ' . $e->getMessage();
                }
            }
            break;
            
        case 2:
            // Site configuration step
            $site_title = trim($_POST['site_title'] ?? '');
            $site_description = trim($_POST['site_description'] ?? '');
            $admin_email = trim($_POST['admin_email'] ?? '');
            $admin_password = $_POST['admin_password'] ?? '';
            
            if (empty($site_title) || empty($admin_email) || empty($admin_password)) {
                $error = 'Semua field wajib diisi.';
            } else {
                try {
                    // Update site settings
                    include 'backend/config/database.php';
                    $database = new Database();
                    $db = $database->getConnection();
                    
                    if ($db) {
                        // Update settings
                        $stmt = $db->prepare("UPDATE settings SET setting_value = ? WHERE setting_key = ?");
                        $stmt->execute([$site_title, 'site_title']);
                        $stmt->execute([$site_description, 'site_description']);
                        
                        // Update admin user
                        $hashed_password = password_hash($admin_password, PASSWORD_DEFAULT);
                        $stmt = $db->prepare("UPDATE users SET email = ?, password = ? WHERE username = 'admin'");
                        $stmt->execute([$admin_email, $hashed_password]);
                        
                        // Create installation lock file
                        file_put_contents('installed.lock', date('Y-m-d H:i:s'));
                        
                        $success = 'Instalasi berhasil! Website Anda siap digunakan.';
                        $step = 3;
                    } else {
                        $error = 'Gagal terhubung ke database.';
                    }
                } catch (Exception $e) {
                    $error = 'Error: ' . $e->getMessage();
                }
            }
            break;
    }
}
?>
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Installer - Fio Trans Cargo Website</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 min-h-screen">
    <div class="container mx-auto px-4 py-8">
        <div class="max-w-2xl mx-auto">
            <!-- Header -->
            <div class="text-center mb-8">
                <h1 class="text-3xl font-bold text-blue-600 mb-2">
                    <i class="fas fa-cog mr-2"></i>Fio Trans Cargo Website
                </h1>
                <p class="text-gray-600">Installer & Setup</p>
            </div>
            
            <!-- Progress Steps -->
            <div class="flex justify-center mb-8">
                <div class="flex items-center space-x-4">
                    <div class="flex items-center">
                        <div class="w-8 h-8 rounded-full <?= $step >= 1 ? 'bg-blue-600 text-white' : 'bg-gray-300' ?> flex items-center justify-center text-sm font-semibold">1</div>
                        <span class="ml-2 text-sm <?= $step >= 1 ? 'text-blue-600' : 'text-gray-500' ?>">Database</span>
                    </div>
                    <div class="w-8 h-0.5 <?= $step >= 2 ? 'bg-blue-600' : 'bg-gray-300' ?>"></div>
                    <div class="flex items-center">
                        <div class="w-8 h-8 rounded-full <?= $step >= 2 ? 'bg-blue-600 text-white' : 'bg-gray-300' ?> flex items-center justify-center text-sm font-semibold">2</div>
                        <span class="ml-2 text-sm <?= $step >= 2 ? 'text-blue-600' : 'text-gray-500' ?>">Konfigurasi</span>
                    </div>
                    <div class="w-8 h-0.5 <?= $step >= 3 ? 'bg-blue-600' : 'bg-gray-300' ?>"></div>
                    <div class="flex items-center">
                        <div class="w-8 h-8 rounded-full <?= $step >= 3 ? 'bg-green-600 text-white' : 'bg-gray-300' ?> flex items-center justify-center text-sm font-semibold">
                            <?= $step >= 3 ? '✓' : '3' ?>
                        </div>
                        <span class="ml-2 text-sm <?= $step >= 3 ? 'text-green-600' : 'text-gray-500' ?>">Selesai</span>
                    </div>
                </div>
            </div>
            
            <!-- Main Content -->
            <div class="bg-white rounded-lg shadow-lg p-8">
                <?php if ($error): ?>
                    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-6">
                        <i class="fas fa-exclamation-triangle mr-2"></i><?= htmlspecialchars($error) ?>
                    </div>
                <?php endif; ?>
                
                <?php if ($success): ?>
                    <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded mb-6">
                        <i class="fas fa-check-circle mr-2"></i><?= htmlspecialchars($success) ?>
                    </div>
                <?php endif; ?>
                
                <?php if ($step == 1): ?>
                    <!-- Step 1: Database Configuration -->
                    <h2 class="text-2xl font-bold mb-6">Konfigurasi Database</h2>
                    <p class="text-gray-600 mb-6">Masukkan informasi database MySQL Anda. Installer akan otomatis membuat database dan tabel yang diperlukan.</p>
                    
                    <form method="POST">
                        <div class="space-y-4">
                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-2">Host Database</label>
                                <input type="text" name="db_host" value="<?= htmlspecialchars($_POST['db_host'] ?? 'localhost') ?>" 
                                       class="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" 
                                       placeholder="localhost" required>
                            </div>
                            
                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-2">Nama Database</label>
                                <input type="text" name="db_name" value="<?= htmlspecialchars($_POST["db_name"] ?? "fio_trans_cargo") ?>" 
                                       class="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" 
                                       placeholder="fio_trans_cargo" required>
                            </div>
                            
                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-2">Username Database</label>
                                <input type="text" name="db_user" value="<?= htmlspecialchars($_POST['db_user'] ?? '') ?>" 
                                       class="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" 
                                       placeholder="root" required>
                            </div>
                            
                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-2">Password Database</label>
                                <input type="password" name="db_pass" 
                                       class="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" 
                                       placeholder="(kosongkan jika tidak ada password)">
                            </div>
                        </div>
                        
                        <button type="submit" class="w-full mt-6 bg-blue-600 text-white py-3 rounded-lg hover:bg-blue-700 transition duration-300">
                            <i class="fas fa-database mr-2"></i>Test Koneksi & Lanjutkan
                        </button>
                    </form>
                    
                <?php elseif ($step == 2): ?>
                    <!-- Step 2: Site Configuration -->
                    <h2 class="text-2xl font-bold mb-6">Konfigurasi Website</h2>
                    <p class="text-gray-600 mb-6">Atur informasi dasar website dan akun administrator.</p>
                    
                    <form method="POST">
                        <div class="space-y-4">
                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-2">Judul Website</label>
                                <input type="text" name="site_title" value="<?= htmlspecialchars($_POST["site_title"] ?? "Fio Trans Cargo") ?>" 
                                       class="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" 
                                       required>
                            </div>
                            
                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-2">Deskripsi Website</label>
                                <textarea name="site_description" rows="3" 
                                          class="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"><?= htmlspecialchars($_POST['site_description'] ?? 'Jasa pengiriman barang terpercaya ke seluruh Indonesia') ?></textarea>
                            </div>
                            
                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-2">Email Administrator</label>
                                <input type="email" name="admin_email" value="<?= htmlspecialchars($_POST['admin_email'] ?? '') ?>" 
                                       class="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" 
                                       required>
                            </div>
                            
                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-2">Password Administrator</label>
                                <input type="password" name="admin_password" 
                                       class="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" 
                                       placeholder="Minimal 8 karakter" required>
                            </div>
                        </div>
                        
                        <button type="submit" class="w-full mt-6 bg-blue-600 text-white py-3 rounded-lg hover:bg-blue-700 transition duration-300">
                            <i class="fas fa-check mr-2"></i>Selesaikan Instalasi
                        </button>
                    </form>
                    
                <?php else: ?>
                    <!-- Step 3: Installation Complete -->
                    <div class="text-center">
                        <div class="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6">
                            <i class="fas fa-check text-green-600 text-2xl"></i>
                        </div>
                        
                        <h2 class="text-2xl font-bold text-green-600 mb-4">Instalasi Berhasil!</h2>
                        <p class="text-gray-600 mb-8">Website Calista Express Anda telah berhasil diinstall dan siap digunakan.</p>
                        
                        <div class="bg-blue-50 p-6 rounded-lg mb-6">
                            <h3 class="font-semibold text-blue-800 mb-3">Langkah Selanjutnya:</h3>
                            <ul class="text-left text-blue-700 space-y-2">
                                <li><i class="fas fa-arrow-right mr-2"></i>Kunjungi <a href="frontend/index.html" class="underline font-semibold">halaman depan website</a></li>
                                <li><i class="fas fa-arrow-right mr-2"></i>Login ke dashboard admin (akan tersedia di versi selanjutnya)</li>
                                <li><i class="fas fa-arrow-right mr-2"></i>Mulai mengelola konten website Anda</li>
                            </ul>
                        </div>
                        
                        <div class="flex space-x-4 justify-center">
                            <a href="frontend/index.html" class="bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 transition duration-300">
                                <i class="fas fa-home mr-2"></i>Lihat Website
                            </a>
                            <a href="backend/" class="bg-gray-600 text-white px-6 py-3 rounded-lg hover:bg-gray-700 transition duration-300">
                                <i class="fas fa-cog mr-2"></i>API Backend
                            </a>
                        </div>
                        
                        <div class="mt-8 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
                            <p class="text-yellow-800 text-sm">
                                <i class="fas fa-info-circle mr-2"></i>
                                <strong>Penting:</strong> Untuk keamanan, hapus file <code>install.php</code> setelah instalasi selesai.
                            </p>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
            
            <!-- Footer -->
            <div class="text-center mt-8 text-gray-500 text-sm">
                <p>&copy; 2025 Calista Express Website. Powered by PHP & Tailwind CSS.</p>
            </div>
        </div>
    </div>
</body>
</html>

